# Generated by Django 4.1.7 on 2023-05-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session_model',
            old_name='id_session',
            new_name='session_id',
        ),
    ]
