# Generated by Django 4.1.7 on 2023-05-26 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_id_session_session_model_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assossiatedto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.workspace'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Workspacemembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Taskmembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspacemembers')),
            ],
        ),
    ]
