# Generated by Django 4.1.7 on 2023-07-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_task_description_workspace_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemembers',
            name='isapproved',
            field=models.BooleanField(default=False),
        ),
    ]
