# Generated by Django 4.1.7 on 2023-07-29 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_notification_notificationbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemembers',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificationbody',
            field=models.TextField(max_length=100),
        ),
    ]
