# Generated by Django 4.1.7 on 2023-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_brifings',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_header',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
