# Generated by Django 4.1.7 on 2023-08-03 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_task_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
