# Generated by Django 4.1.7 on 2023-08-03 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_task_end_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmembers',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='taskmembers',
            name='isapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Smallmissions',
        ),
    ]
